/* Generated by Yosys 0.67+102 (git sha1 07a615a28-dirty, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 15.2.1) */

(* top =  1  *)
(* src = "C:\\Users\\kaush.KAUSHIK\\Documents\\Codex\\2026-07-09\\vericore-ai\\test.v:1.1-9.10" *)
module test(A, B, Y);
  (* src = "C:\\Users\\kaush.KAUSHIK\\Documents\\Codex\\2026-07-09\\vericore-ai\\test.v:2.17-2.18" *)
  input A;
  wire A;
  (* src = "C:\\Users\\kaush.KAUSHIK\\Documents\\Codex\\2026-07-09\\vericore-ai\\test.v:3.17-3.18" *)
  input B;
  wire B;
  (* src = "C:\\Users\\kaush.KAUSHIK\\Documents\\Codex\\2026-07-09\\vericore-ai\\test.v:4.17-4.18" *)
  output Y;
  wire Y;
  assign Y = A &(* src = "C:\\Users\\kaush.KAUSHIK\\Documents\\Codex\\2026-07-09\\vericore-ai\\test.v:7.12-7.17" *)  B;
endmodule
