"""
Documentation Report Schema.

Represents the complete output of the VeriCore AI pipeline.
"""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field

from backend.app.schemas.debug_report import DebugReport
from backend.app.schemas.requirement_spec import RequirementSpec
from backend.app.schemas.rtl_design import RTLDesign
from backend.app.schemas.simulation_result import SimulationResult
from backend.app.schemas.synthesis_result import SynthesisResult
from backend.app.schemas.verification_plan import VerificationPlan


class DocumentationReport(BaseModel):
    """
    Complete project report generated by VeriCore AI.
    """

    requirement_text: str = Field(
        ...,
        description="Original natural language requirement.",
    )

    requirement_spec: RequirementSpec = Field(
        ...,
        description="Structured requirement specification.",
    )

    rtl_design: RTLDesign = Field(
        ...,
        description="Generated RTL design.",
    )

    verification_plan: VerificationPlan = Field(
        ...,
        description="Generated verification plan.",
    )

    rtl_source: str = Field(
        ...,
        description="Generated Verilog RTL source.",
    )

    testbench_source: str = Field(
        ...,
        description="Generated Verilog testbench.",
    )

    simulation_result: SimulationResult | None = Field(
        default=None,
        description="Simulation results.",
    )

    synthesis_result: SynthesisResult | None = Field(
        default=None,
        description="RTL synthesis results.",
    )

    post_synthesis_simulation_result: SimulationResult | None = Field(
        default=None,
        description="Post-synthesis netlist simulation results.",
    )

    debug_report: DebugReport | None = Field(
        default=None,
        description="Debug report if simulation or synthesis failed.",
    )

    generated_files: dict[str, str] = Field(
        default_factory=dict,
        description="Generated file paths.",
    )

    generated_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Report generation timestamp.",
    )

    success: bool = Field(
        default=True,
        description="Overall pipeline success.",
    )
    post_synthesis_simulation_result=(
    post_synthesis_simulation_result
),