"""
Schemas for generated pipeline artifacts exposed to the frontend.
"""

from pydantic import BaseModel, Field


class PipelineArtifactPaths(BaseModel):
    """
    Files generated by a completed pipeline run.
    """

    rtl: str | None = None
    testbench: str | None = None
    simulation_output: str | None = None
    simulation_waveform: str | None = None
    synthesis_design: str | None = None
    synthesis_script: str | None = None
    synthesis_netlist: str | None = None
    synthesis_report: str | None = None
    synthesis_schematic_svg: str | None = None
    synthesis_schematic_dot: str | None = None
    post_synthesis_simulation_output: str | None = None
    post_synthesis_waveform: str | None = None
    documentation: str | None = None


class PipelineArtifactDownloadUrls(BaseModel):
    """
    API URLs for retrieving generated artifact files.
    """

    rtl: str | None = None
    testbench: str | None = None
    simulation_output: str | None = None
    simulation_waveform: str | None = None
    synthesis_netlist: str | None = None
    synthesis_report: str | None = None
    synthesis_schematic_svg: str | None = None
    synthesis_schematic_dot: str | None = None
    post_synthesis_simulation_output: str | None = None
    post_synthesis_waveform: str | None = None
    documentation: str | None = None


class PipelineArtifactsResponse(BaseModel):
    """
    Read-only view of artifacts generated for a pipeline project.
    """

    module_name: str = Field(
        ...,
        description="Generated top-level module/project name.",
    )
    project_path: str = Field(
        ...,
        description="Generated project directory path.",
    )
    artifact_paths: PipelineArtifactPaths
    download_urls: PipelineArtifactDownloadUrls

    rtl_source: str | None = None
    testbench_source: str | None = None
    simulation_output: str | None = None
    simulation_waveform_source: str | None = None
    synthesis_report: str | None = None
    post_synthesis_simulation_output: str | None = None
    post_synthesis_waveform_source: str | None = None
    documentation_markdown: str | None = None
