from pydantic import BaseModel, Field


class TestCase(BaseModel):
    """
    Represents a verification test scenario.
    """

    name: str

    description: str

    stimulus: str

    expected_result: str


class VerificationPlan(BaseModel):
    """
    Structured verification plan generated by AI.
    """

    test_cases: list[TestCase] = Field(
        default_factory=list
    )

    assertions: list[str] = Field(
        default_factory=list
    )

    coverage_points: list[str] = Field(
        default_factory=list
    )