from __future__ import annotations

from pydantic import BaseModel, Field

from backend.app.schemas.test_vector import TestVector


class TestCase(BaseModel):
    """
    Represents a high-level verification scenario.
    """

    name: str

    description: str

    stimulus: str

    expected_result: str


class VerificationPlan(BaseModel):
    """
    Structured verification plan generated by AI.
    """

    test_cases: list[TestCase] = Field(
        default_factory=list
    )

    test_vectors: list[TestVector] = Field(
        default_factory=list
    )

    assertions: list[str] = Field(
        default_factory=list
    )

    coverage_points: list[str] = Field(
        default_factory=list
    )