"use client";

import { Download, PlayCircle } from "lucide-react";

import CodeViewer from "@/components/pipeline/CodeViewer";
import MissingPipelineState from "@/components/pipeline/MissingPipelineState";
import StatusBadge from "@/components/pipeline/StatusBadge";
import WaveformViewer from "@/components/waveform/WaveformViewer";
import { usePipelineArtifacts } from "@/hooks/usePipelineArtifacts";
import { extractBooleanFromReport } from "@/lib/pipeline-report";
import { getArtifactUrl } from "@/services/pipelineService";

export default function SimulationPage() {
  const {
    latestPipelineResult,
    moduleName,
    artifacts,
    loading,
    error,
    isHydrated,
  } = usePipelineArtifacts();

  if (!isHydrated) {
    return <p className="text-sm text-muted-foreground">Loading...</p>;
  }

  if (!latestPipelineResult || !moduleName) {
    return <MissingPipelineState />;
  }

  const compileSuccess = extractBooleanFromReport(
    artifacts?.documentation_markdown,
    ["Compile Success"],
  );

  const simulationSuccess = extractBooleanFromReport(
    artifacts?.documentation_markdown,
    ["Simulation Success"],
  );

  const waveformUrl = getArtifactUrl(
    artifacts?.download_urls.simulation_waveform ?? null,
  );

  return (
    <div className="space-y-6">
      <div>
        <h1 className="flex items-center gap-2 text-3xl font-bold">
          <PlayCircle className="h-7 w-7" />
          Simulation
        </h1>

        <p className="mt-2 text-muted-foreground">
          Module: {moduleName}
        </p>
      </div>

      {error && (
        <p className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">
          {error}
        </p>
      )}

      <section className="grid gap-4 md:grid-cols-3">
        <div className="rounded-xl border bg-card p-4 shadow-sm">
          <p className="text-sm text-muted-foreground">Compilation</p>
          <div className="mt-2">
            <StatusBadge success={compileSuccess} />
          </div>
        </div>

        <div className="rounded-xl border bg-card p-4 shadow-sm">
          <p className="text-sm text-muted-foreground">Simulation</p>
          <div className="mt-2">
            <StatusBadge success={simulationSuccess} />
          </div>
        </div>

        <div className="rounded-xl border bg-card p-4 shadow-sm">
          <p className="text-sm text-muted-foreground">Waveform</p>

          {waveformUrl ? (
            <a
              href={waveformUrl}
              className="mt-2 inline-flex items-center gap-2 text-sm font-medium underline-offset-4 hover:underline"
            >
              <Download className="h-4 w-4" />
              Download VCD
            </a>
          ) : (
            <p className="mt-2 text-sm font-medium">Unavailable</p>
          )}
        </div>
      </section>

      <section className="rounded-xl border bg-card p-6 shadow-sm">
        <div className="mb-4">
          <h2 className="text-lg font-semibold">Simulation Output</h2>

          <p className="mt-1 break-all text-sm text-muted-foreground">
            {artifacts?.artifact_paths.simulation_output ?? "Unavailable"}
          </p>
        </div>

        {loading ? (
          <p className="text-sm text-muted-foreground">
            Loading simulation output...
          </p>
        ) : (
          <CodeViewer
            code={artifacts?.simulation_output ?? null}
            emptyMessage="Simulation output is not available."
          />
        )}
      </section>

      <section className="rounded-xl border bg-card p-6 shadow-sm">
        <div className="mb-4">
          <h2 className="text-lg font-semibold">Waveform</h2>

          <p className="mt-1 text-sm text-muted-foreground">
            Simulation waveform generated by Icarus Verilog.
          </p>
        </div>

        {loading ? (
          <p className="text-sm text-muted-foreground">
            Loading waveform...
          </p>
        ) : (
          <WaveformViewer
            vcdContent={
              artifacts?.simulation_waveform_source ?? null
            }
          />
        )}
      </section>
    </div>
  );
}
